name = "MakeGlassBox"
uuid = "98fafadc-0a2f-4a93-9dda-8d278c8022c2"
authors = ["Chia-Yu Hu <cyhu.astro@gmail.com>", "Pei-Cheng Tung <pctung0224@gmail.com>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
